### PR TITLE
Added new features to spf.pl

### PR DESCRIPTION
**Pull request by randolf**

### CODE REVIEW

**Comment by jschauma** [comment]
Hey - thanks a lot for the PR!  A few notes that would be great to get addressed before I merge this:
- Could you illustrate the need for the '-b' option? I.e., what's the difference in output given an example?
- You can ditch the '-j' option altogether and have '-f json' as an option; we'd just bump the major version number to indicate non-compatibility.
- Could you update the manual page in doc/spf.1?  The README is generated from that.

Thanks!

**Comment by randolf** [comment]
> Hey - thanks a lot for the PR! A few notes that would be great to get addressed before I merge this:

You're welcome, and thank you so much for responding so quickly!

> * Could you illustrate the need for the '-b' option? I.e., what's the difference in output given an example?

No problem.  When I query for an SPF record that yields a high quantity of IP addresses, the total is presented in scientific notation.  Here's what it looks like when I query the SPF record for `google.com`:

`    Total # of ip6 addresses        : 2.97105609428491e+28    `

With the -b option I added (along with the various implementation points in the source code -- search for "$OPTS{'b'}" to see all of them), the output includes the entire/exact value without resorting to scientific notation:

`    Total # of ip6 addresses        : 29710560942849126597578981376    `

(This effects all output formats consistently.)

By the way, it took a bit of extra work to make sure the number was exact instead of it being rounded off, but that was actually a fun task so I'm glad I had the extra time to spare.  =)

(I'm tempted to add an option to insert commas for easier readability, but this would only apply for the text format since the json and perl formats will most likely be used for automated systems that probably won't be expecting numbers to include commas.  There are some other features I'd like to add too, which will be helpful to me and hopefully others as well, but I think it will be easier for code reviews and any debugging that might be needed if we don't add too many features all at once.)

> * You can ditch the '-j' option altogether and have '-f json' as an option; we'd just bump the major version number to indicate non-compatibility.

i didn't want to break backward compatibility for people who are using this feature.  I did refactor the code so that removing this option will be easy in the future (behind the scenes "-j" now just fills in "-f json" and there's no other code that specifically tests for "-j" anymore).

My recommendation is to log a WARNING that "-j" will be phased out (and replaced with "-f json") after a certain date or upon reaching version 0.9 or version 1.0.  This way, if users are relying on this option they won't be surprised by its sudden-and-unexpected disappearance when they update.

> * Could you update the manual page in doc/spf.1?  The README is generated from that.

Yes, I'll gladly do this.

> Thanks!

If you have a FreeBSD or NetBSD system available, could you check that I got the additional pkgsrc module name correct?  I'd appreciate it as I don't have these systems available on-hand anymore (I used to use NetBSD extensively, so I know where to check to make a reasonable "educated guess").

**Comment by jschauma** [comment]
Awesome, thanks for your reply!  So I think I'd like to do the following:

- ditch '-j' and just use '-f' (phasing out with a warning seems overkill to me given the very small userbase this tool has; just bumping the major version number should be sufficient)
- make "big int" use the default (and only) option; I don't believe anybody really wants scientific notation numbers :-)
- if you have logic to pretty-ify the large number in a local-specific manner, that'd be neat, but happy to merge that later

Does that sound good?

**Comment by randolf** [comment]
> Awesome, thanks for your reply! So I think I'd like to do the following:
> 
> * ditch '-j' and just use '-f' (phasing out with a warning seems overkill to me given the very small userbase this tool has; just bumping the major version number should be sufficient)

Done (your reasoning makes sense to me).  Code and documentation updated accordingly, and the -j option has been removed.

> * make "big int" use the default (and only) option; I don't believe anybody really wants scientific notation numbers :-)

Done.  Code updated accordingly, and the -b option has been removed.

> * if you have logic to pretty-ify the large number in a local-specific manner, that'd be neat, but happy to merge that later

I don't have that at present, and it's a lower priority for me, but I will try to get to it as part of attempting to address items in the TODO list at a later date.

> Does that sound good?

Yes.  Thanks!  Various files have been updated and I hope I didn't miss anything (please let me know whatever I did miss if you notice anything no matter how small).

P.S.:  Please also see my changes to the README.md file -- I don't know where to add many portions in the templates (which I also updated based on what already seems to be there), so I added to README.md (again) in the hopes that this will at least be easier for copy-and-paste before regenerating this file from your scripts.

**Comment by jschauma** [comment]
That looks great - thanks so much!

**Pull request merged**
